#!/bin/sh
set -eu
REPO_ROOT="$(cd "$(dirname "$0")/.."; pwd)"

export PYTHONPATH="$REPO_ROOT/external/katana/scripts:$REPO_ROOT/scripts:${PYTHONPATH:+:${PYTHONPATH}}"
python3 -m katana_requirements "$@" || \
  (echo "HINT:   If there are ImportErrors make sure you have the yaml and packaging python packages" \
        "installed. (Apt packages: python3-yaml, python3-packaging)" &&
        false)
