{% set version %}{% include "version.txt" %}{% endset %}

package:
  name: katana
  version: {{ version }}

source:
  path: ../

build:
  number: 9
  script_env:
    - KATANA_DOCS_OUTPUT
#    - CMAKE_BUILD_PARALLEL_LEVEL

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('numactl-devel') }}
    - cmake>=3.19
    - cython>=0.29.12
    - make
    - pyarrow {{ arrow_cpp }}
    - python {{ python }}
    # Workaround for upstream sphinx instability [1]
    #
    # [1] https://github.com/sphinx-doc/sphinx/issues/8880
    #
    # TODO(ddn): revisit (each instance of sphinx<3.5.0, there are 4)
    - sphinx<3.5.0
  host:
    - jinja2
    - cython>=0.29.12
    - pyarrow {{ arrow_cpp }}
    - numba>=0.50,<1.0a0
    - python {{ python }}
    - sphinx<3.5.0
    - {{ compiler('cxx') }}
    - {{ cdt('numactl-devel') }}
    - arrow-cpp {{ arrow_cpp }}
    - aws-sdk-cpp>=1.7.164,<2.0a0
    - backward-cpp>=1.4
    - boost-cpp>=1.71
    - elfutils
    - fmt>=6.2.1
    - howardhinnant_date>=3.0.0
    - libcurl>=7.66
    - libxml2>=2.9.10
    - llvm>=8
    - ncurses>=6.1
    - nlohmann_json>=3.7.3
    - openblas>=0.3.12
    - zlib>=1.2.11

outputs:
  - name: katana-cpp
    files:
      - include/katana/**
      - include/tsuba/**
      - lib/libkatana_galois.so*
      - lib/libkatana_support.a
      - lib/libtsuba.so*
      - lib/libtsuba-preload.so
      - lib/cmake/Katana/**
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ cdt('numactl-devel') }}
        - arrow-cpp {{ arrow_cpp }}
        - aws-sdk-cpp>=1.7.164,<2.0a0
        - backward-cpp>=1.4
        - boost-cpp>=1.71
        - elfutils
        - fmt>=6.2.1
        - howardhinnant_date>=3.0.0
        - libcurl>=7.66
        - libxml2>=2.9.10
        - llvm>=8
        - ncurses>=6.1
        - nlohmann_json>=3.7.3
        - openblas>=0.3.12
        - zlib>=1.2.11
      host:
        - {{ cdt('numactl-devel') }}
        - arrow-cpp {{ arrow_cpp }}
        - aws-sdk-cpp>=1.7.164,<2.0a0
        - backward-cpp>=1.4
        - boost-cpp>=1.71
        - elfutils
        - fmt>=6.2.1
        - howardhinnant_date>=3.0.0
        - libcurl>=7.66
        - libxml2>=2.9.10
        - llvm>=8
        - ncurses>=6.1
        - nlohmann_json>=3.7.3
        - openblas>=0.3.12
        - zlib>=1.2.11
      run:
        - boost-cpp
        - arrow-cpp
        - aws-sdk-cpp
        - fmt
        - nlohmann_json
        - openblas
        - howardhinnant_date
        - libcurl
        - backward-cpp
        - elfutils
    run_exports:
      - {{ pin_subpackage('katana-cpp', max_pin='x.x.x') }}
    test:
      requires:
        - {{ compiler('cxx') }}
        - {{ cdt('numactl') }}
        - cmake>=3.13
        - make
      files:
        - test_app/CMakeLists.txt
        - test_app/test_app.cpp
      script: run_test_cpp.sh
  - name: katana-python
    files:
      - lib/python*/site-packages/katana_python-*/**
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ cdt('numactl-devel') }}
        - arrow-cpp {{ arrow_cpp }}
        - aws-sdk-cpp>=1.7.164,<2.0a0
        - backward-cpp>=1.4
        - boost-cpp>=1.71
        - elfutils
        - fmt>=6.2.1
        - howardhinnant_date>=3.0.0
        - libcurl>=7.66
        - libxml2>=2.9.10
        - llvm>=8
        - ncurses>=6.1
        - nlohmann_json>=3.7.3
        - openblas>=0.3.12
        - zlib>=1.2.11
        - jinja2
        - cython>=0.29.12
        - pyarrow {{ arrow_cpp }}
        - numba>=0.50,<1.0a0
        - python {{ python }}
        - sphinx<3.5.0
      host:
        - {{ cdt('numactl-devel') }}
        - arrow-cpp {{ arrow_cpp }}
        - aws-sdk-cpp>=1.7.164,<2.0a0
        - backward-cpp>=1.4
        - boost-cpp>=1.71
        - elfutils
        - fmt>=6.2.1
        - howardhinnant_date>=3.0.0
        - libcurl>=7.66
        - libxml2>=2.9.10
        - llvm>=8
        - ncurses>=6.1
        - nlohmann_json>=3.7.3
        - openblas>=0.3.12
        - zlib>=1.2.11
        - {{ pin_subpackage('katana-cpp', exact=True) }}
        - jinja2
        - cython>=0.29.12
        - pyarrow {{ arrow_cpp }}
        - numba>=0.50,<1.0a0
        - python {{ python }}
        - sphinx<3.5.0
      run:
        - {{ pin_subpackage('katana-cpp', exact=True) }}
        - {{ pin_compatible('numba') }}
        - {{ pin_compatible('pyarrow') }}
        - {{ pin_compatible('numpy') }}
        - python {{ python }}
    run_exports:
      - {{ pin_subpackage('katana-python', max_pin='x.x.x') }}
    test:
      requires:
        - jupyter
        - pytest
      source_files:
        - python/tests
        - python/examples/jupyter
      script: run_test_python.sh
  - name: katana-bin
    files:
      - bin/graph-convert
      - bin/graph-convert-huge
      - bin/graph-properties-convert
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ cdt('numactl-devel') }}
        - arrow-cpp {{ arrow_cpp }}
        - aws-sdk-cpp>=1.7.164,<2.0a0
        - backward-cpp>=1.4
        - boost-cpp>=1.71
        - elfutils
        - fmt>=6.2.1
        - howardhinnant_date>=3.0.0
        - libcurl>=7.66
        - libxml2>=2.9.10
        - llvm>=8
        - ncurses>=6.1
        - nlohmann_json>=3.7.3
        - openblas>=0.3.12
        - zlib>=1.2.11
      host:
        - {{ cdt('numactl-devel') }}
        - arrow-cpp {{ arrow_cpp }}
        - aws-sdk-cpp>=1.7.164,<2.0a0
        - backward-cpp>=1.4
        - boost-cpp>=1.71
        - elfutils
        - fmt>=6.2.1
        - howardhinnant_date>=3.0.0
        - libcurl>=7.66
        - libxml2>=2.9.10
        - llvm>=8
        - ncurses>=6.1
        - nlohmann_json>=3.7.3
        - openblas>=0.3.12
        - zlib>=1.2.11
        - {{ pin_subpackage('katana-cpp', exact=True) }}
      run:
        - {{ pin_subpackage('katana-cpp', exact=True) }}
        #- {{ pin_subpackage('katana-python', exact=True) }} <- Add this if any Python scripts are added to bin/
    test:
      commands:
        - graph-convert --help > /dev/null
        - graph-properties-convert --help > /dev/null

about:
  home: https://katanagraph.com/
  license: BSD
  license_file: LICENSE.txt
  summary: Library for building parallel graph algorithms.

extra:
  repository: https://github.com/KatanaGraph/katana
  recipe-maintainers:
    - katanagraph
    - amp
