package:
  name: katana
  version: "{{ KATANA_VERSION }}"

source:
  path: ../

build:
  number: 0
  script_env:
    - KATANA_VERSION

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('numactl-devel') }}
    - cmake>=3.17
    - cython>=0.29.12
    - make
    - pyarrow {{ arrow_cpp }}
    - python {{ python }}
    - sphinx>=3.5.1
    - pygithub
    - packaging
    - libxml2>=2.9.10
  host:
    - jinja2
    - cython>=0.29.12
    - pyarrow {{ arrow_cpp }}
    # TODO(amp): Remove as soon as libthrift/arrow-cpp are fixed. https://github.com/conda-forge/arrow-cpp-feedstock/issues/461
    - libthrift 0.14.1
    - numba>=0.50,<1.0a0
    - python {{ python }}
    - sphinx>=3.5.1
    - {{ compiler('cxx') }}
    - {{ cdt('numactl-devel') }}
    - arrow-cpp {{ arrow_cpp }}
    - backward-cpp>=1.4
    - boost-cpp>=1.74
    - elfutils
    - fmt>=6.2.1
    - libcurl>=7.66
    - libxml2>=2.9.10
    - llvm>=8
    - ncurses>=6.1
    - nlohmann_json>=3.7.3
    - openblas>=0.3.12
    - zlib>=1.2.11

outputs:
  - name: katana-cpp
    about:
      summary: C++ library for parallel and distributed graph analytics and processing. (Open-source)
    files:
      - include/katana/**
      - include/tsuba/**
      - lib/libkatana_galois.so*
      - lib/libkatana_support.so*
      - lib/libtsuba.so*
      - lib/cmake/Katana/**
      - lib/katana/plugins/.placeholder
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ cdt('numactl-devel') }}
      host:
        - {{ cdt('numactl-devel') }}
        - arrow-cpp {{ arrow_cpp }}
        # TODO(amp): Remove as soon as libthrift/arrow-cpp are fixed. https://github.com/conda-forge/arrow-cpp-feedstock/issues/461
        - libthrift 0.14.1
        - backward-cpp>=1.4
        - boost-cpp>=1.74
        - elfutils
        - fmt>=6.2.1
        - libcurl>=7.66
        - libxml2>=2.9.10
        - llvm>=8
        - ncurses>=6.1
        - nlohmann_json>=3.7.3
        - openblas>=0.3.12
        - zlib>=1.2.11
      run:
        - boost-cpp
        - arrow-cpp
        # TODO(amp): Remove as soon as libthrift/arrow-cpp are fixed. https://github.com/conda-forge/arrow-cpp-feedstock/issues/461
        - libthrift 0.14.1
        - fmt
        - nlohmann_json
        - libcurl
        - backward-cpp
        - elfutils
        - libxml2
    run_exports:
      - {{ pin_subpackage('katana-cpp', max_pin='x.x.x') }}
    test:
      requires:
        - {{ compiler('cxx') }}
        - cmake>=3.17
        - make
      files:
        - test_app/CMakeLists.txt
        - test_app/test_app.cpp
      script: run_test_cpp.sh
  - name: katana-python
    about:
      summary: Python library for parallel and distributed graph analytics and processing. (Open-source)
    files:
      - lib/python*/site-packages/katana_python-*/**
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ cdt('numactl-devel') }}
      host:
        - {{ pin_subpackage('katana-cpp', exact=True) }}
        - jinja2
        - cython>=0.29.12
        - pyarrow {{ arrow_cpp }}
        - numba>=0.50,<1.0a0
        - python {{ python }}
        - sphinx>=3.5.1
      run:
        - {{ pin_subpackage('katana-cpp', exact=True) }}
        - numba
        - numpy
        - pyarrow
    run_exports:
      - {{ pin_subpackage('katana-python', max_pin='x.x.x') }}
    test:
      requires:
        - jupyter
        - pytest

        # The dependencies for pytest-notebook are incomplete, add them manually
        - pytest-notebook
        - attrs<21,>=19
        - nbconvert<6
        - pexpect
      source_files:
        - tools/graph-convert/test-inputs
        - python/test
        - python/examples/notebooks
      script: run_test_python.sh
  - name: katana-tools
    about:
      summary: Tools for converting Katana graphs. (Open-source)
    files:
      - bin/graph-convert
      - bin/graph-convert-huge
      - bin/graph-properties-convert
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ cdt('numactl-devel') }}
      host:
        - {{ pin_subpackage('katana-cpp', exact=True) }}
      run:
        - {{ pin_subpackage('katana-cpp', exact=True) }}
        #- {{ pin_subpackage('katana-python', exact=True) }} <- Add this if any Python scripts are added to bin/
    test:
      commands:
        - graph-convert --help > /dev/null
        - graph-properties-convert --help > /dev/null

about:
  home: https://katanagraph.com/
  license: BSD
  license_file: LICENSE.txt

extra:
  repository: https://github.com/KatanaGraph/katana
  recipe-maintainers:
    - katanagraph
    - amp
