package:
  name: katana
  version: "{{ KATANA_VERSION }}"

source:
  path: ../

build:
  number: 0
  script_env:
    - KATANA_VERSION

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('numactl-devel') }}
    - breathe {{ breathe }}
    - cmake {{ cmake }}
    - cython {{ cython }}
    - doxygen {{ doxygen }}
    - nbsphinx {{ nbsphinx }}
    - make {{ make }}
    - packaging {{ packaging }}
    - pandoc {{ pandoc }}
    - pyarrow {{ arrow_cpp }}
    - pydata-sphinx-theme {{ pydata_sphinx_theme }}
    - pygithub {{ pygithub }}
    - python {{ python }}
    - sphinx {{ sphinx }}
    - sphinx-copybutton {{ sphinx_copybutton }}
    - sphinx-tabs {{ sphinx_tabs }}
  host:
    - jinja2 {{ jinja2 }}
    - cython {{ cython }}
    - pyarrow {{ arrow_cpp }}
    - numba {{ numba }}
    - python {{ python }}
    - {{ compiler('cxx') }}
    - {{ cdt('numactl-devel') }}
    - arrow-cpp {{ arrow_cpp }}
    - backward-cpp {{ backward_cpp }}
    - benchmark {{ benchmark }}
    - boost-cpp {{ boost_cpp }}
    - elfutils {{ elfutils }}
    - fmt {{ fmt }}
    - libcurl {{ libcurl }}
    - libxml2 {{ libxml2 }}
    - llvmdev {{ llvmdev }}
    - ncurses {{ ncurses }}
    - nlohmann_json {{ nlohmann_json }}
    - openblas {{ openblas }}
    - zlib {{ zlib }}

outputs:
  - name: katana-cpp
    about:
      summary: C++ library for parallel and distributed graph analytics and processing. (Open-source)
    files:
      - include/katana/**
      - include/tsuba/**
      - lib/libkatana_galois.so*
      - lib/libkatana_support.so*
      - lib/libtsuba.so*
      - lib/cmake/Katana/**
      - lib/katana/plugins/.placeholder
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ cdt('numactl-devel') }}
        - python {{ python }}
      host:
        - {{ cdt('numactl-devel') }}
        - arrow-cpp {{ arrow_cpp }}
        - backward-cpp {{ backward_cpp }}
        - benchmark {{ benchmark }}
        - boost-cpp {{ boost_cpp }}
        - elfutils {{ elfutils }}
        - fmt {{ fmt }}
        - libcurl {{ libcurl }}
        - libxml2 {{ libxml2 }}
        - llvmdev {{ llvmdev }}
        - ncurses {{ ncurses }}
        - nlohmann_json {{ nlohmann_json }}
        - openblas {{ openblas }}
        - zlib {{ zlib }}
        - python {{ python }}
      run:
        - boost-cpp
        - arrow-cpp
        - nlohmann_json
        - libcurl
        - backward-cpp
        - elfutils
        - libxml2
    run_exports:
      - {{ pin_subpackage('katana-cpp', max_pin='x.x.x') }}
    test:
      requires:
        - {{ compiler('cxx') }}
        - cmake {{ cmake }}
        - make {{ make }}
      files:
        - test_app/CMakeLists.txt
        - test_app/test_app.cpp
      script: run_test_cpp.sh
  - name: katana-python
    about:
      summary: Python library for parallel and distributed graph analytics and processing. (Open-source)
    files:
      - lib/python*/site-packages/katana_python-*/**
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ cdt('numactl-devel') }}
        - breathe {{ breathe }}
        - doxygen {{ doxygen }}
        - nbsphinx {{ nbsphinx }}
        - pandoc {{ pandoc }}
        - pydata-sphinx-theme {{ pydata_sphinx_theme }}
        - sphinx {{ sphinx }}
        - sphinx-copybutton {{ sphinx_copybutton }}
        - sphinx-tabs {{ sphinx_tabs }}
        - python {{ python }}
      host:
        - {{ pin_subpackage('katana-cpp', exact=True) }}
        - jinja2 {{ jinja2 }}
        - cython {{ cython }}
        - pyarrow {{ arrow_cpp }}
        - numba {{ numba }}
        - numpy {{ numpy }}
        - python {{ python }}
        - pandas {{ pandas }}
        - fmt {{ fmt }}
      run:
        - {{ pin_subpackage('katana-cpp', exact=True) }}
        - numba
        - numpy
        - pyarrow
        - pandas
    run_exports:
      - {{ pin_subpackage('katana-python', max_pin='x.x.x') }}
    test:
      requires:
        - jupyter {{ jupyter }}
        - pytest {{ pytest }}

        # The dependencies for pytest-notebook are incomplete, add them manually
        - pytest-notebook {{ pytest_notebook }}
        - jupyter_client {{ jupyter_client }}
        - attrs {{ attrs }}
        - nbconvert {{ nbconvert }}
        - mistune {{ mistune }}
        - pexpect {{ pexpect }}
      source_files:
        - tools/graph-convert/test-inputs
        - python/test
        - python/examples/notebooks
      script: run_test_python.sh
  - name: katana-tools
    about:
      summary: Tools for converting Katana graphs. (Open-source)
    files:
      - bin/graph-convert
      - bin/graph-convert-huge
      - bin/graph-properties-convert
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ cdt('numactl-devel') }}
      host:
        - {{ pin_subpackage('katana-cpp', exact=True) }}
        - fmt {{ fmt }}
      run:
        - {{ pin_subpackage('katana-cpp', exact=True) }}
        - llvm
        #- {{ pin_subpackage('katana-python', exact=True) }} <- Add this if any Python scripts are added to bin/
    test:
      commands:
        - graph-convert --help > /dev/null
        - graph-properties-convert --help > /dev/null

about:
  home: https://katanagraph.com/
  license: BSD
  license_file: LICENSE.txt

extra:
  repository: https://github.com/KatanaGraph/katana
  recipe-maintainers:
    - katanagraph
    - amp
