include(CheckSymbolExists)

if(CLOCK_GETTIME_FOUND)

else()
  set(CMAKE_REQUIRED_DEFINITIONS -D_GNU_SOURCE)
  CHECK_SYMBOL_EXISTS(clock_gettime time.h HAVE_CLOCK_GETTIME_INTERNAL)
  if(HAVE_CLOCK_GETTIME_INTERNAL)
    message(STATUS "clock_gettime found")
    set(CLOCK_GETTIME_FOUND "${HAVE_CLOCK_GETTIME_INTERNAL}")
  else()
    set(CMAKE_REQUIRED_LIBRARIES "-lrt")
    CHECK_SYMBOL_EXISTS(clock_gettime time.h HAVE_CLOCK_GETTIME_INTERNAL_RT)
    if(HAVE_CLOCK_GETTIME_INTERNAL_RT)
      message(STATUS "clock_gettime found (in librt)")
      set(CLOCK_GETTIME_FOUND "${HAVE_CLOCK_GETTIME_INTERNAL}")
      set(CLOCK_GETTIME_LIBRARIES rt)
    endif()
  endif()
endif()
