{% set version %}{% include "version.txt" %}{% endset %}

# Check environment variables to determine build context
{% set ci_build = environ.get("CI", False) %}
{% set dev_build = environ.get("GALOIS_DEV_BUILD", ci_build) %}

# For dev builds, add ".devN" to the version number, for N being the git commit count since the last tag.
# This makes the build come BEFORE the plain version.
{% set version %}{{ version }}{{ ".dev" + environ.get("GIT_DESCRIBE_NUMBER", "") if dev_build }}{% endset %}
# The number is the github run number or if that is not set the git describe number (commit count since last tag).
{% set build_number = environ.get("GITHUB_RUN_NUMBER", environ.get("GIT_DESCRIBE_NUMBER")) %}

package:
  name: galois-python
  version: {{ version }}

source:
  path: ../../

build:
  number: {{ build_number }}
  # For dev builds, the build string includes the git hash and a tag stating where the build is happening.
  {% if dev_build %}
  string: {{ environ.get("GIT_DESCRIBE_HASH") }}_{{ "ci_" if ci_build }}{{ build_number }}
  {% endif %}
  script_env:
    - GALOIS_DOCS_OUTPUT

requirements:
  build:
    - python
    - scikit-build
    - make
    - jinja2
    - {{ compiler('cxx') }}
    - galois={{ version }}
    - cython>=0.29.12
    - numba>=0.50,<1.0
    - pyarrow
    - sphinx
  host:
    - python
    - scikit-build
    - jinja2
    - {{ compiler('cxx') }}
    - galois={{ version }}
    - cython>=0.29.12
    - numba>=0.50,<1.0
    - pyarrow
  run:
    - python
    - galois={{ version }}
    - numba
    - pyarrow

test:
  requires:
    - jupyter
    - pytest
    - numpy
  source_files:
    - tests
    - python/examples/jupyter
  

about:
  home: https://katanagraph.com/
  license: BSD
  license_file: LICENSE.txt
  summary: A Python interface to the Galois library for building parallel graph algorithms.

extra:
  recipe-maintainers:
    - katanagraph
    - amp
