name: Jira Message Check
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Message For Jira Tag
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: 'JIRA: (KAT\-[0-9]+|NOJIRA)$'
          error: 'You need at least one "JIRA: KAT-<issue number>" line below the title line. If there is no jira associated with this PR/commit you may also use JIRA: NOJIRA. Please see docs/contributing/git-style.rst#submitting-changes for examples'
          excludeTitle: 'true'
          excludeDescription: 'true'
          checkAllCommitMessages: 'false'
